# Database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=${DB_URL}

# Messaging Rabbit MQ
rabbitmq-host=${RABBIT_HOST}
rabbitmq-port=${RABBIT_PORT}
rabbitmq-username=${RABBIT_USER}
rabbitmq-password=${RABBIT_PASSWORD}
# Channel called suspicious_transfers
mp.messaging.outgoing.antifraud-out.connector=smallrye-rabbitmq
mp.messaging.outgoing.antifraud-out.exchange.name=suspicious_transfers
mp.messaging.outgoing.antifraud-out.exchange.type=fanout

# Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true

quarkus.http.port = ${BANK_API_PORT}

# Logs
# In a development environment, keep the log human-readable.
%dev.quarkus.log.console.json.enabled=false
# In a production environment (Cloud/Docker), enable pure JSON for the robots (ELK/Datadog) to read.
%prod.quarkus.log.console.json.enabled=true