quarkus.http.port=${ANTIFRAUD_API_PORT}

#RabbitMQ configurations
rabbitmq-host=${RABBIT_HOST}
rabbitmq-port=${RABBIT_PORT}
rabbitmq-username=${RABBIT_USER}
rabbitmq-password=${RABBIT_PASSWORD}

#Queue configurations
mp.messaging.incoming.frauds-in.connector=smallrye-rabbitmq
mp.messaging.incoming.frauds-in.queue.name=queue_fraud_analysis
mp.messaging.incoming.frauds-in.exchange.type=fanout
mp.messaging.incoming.frauds-in.exchange.name=suspicious_transfers

# URL
quarkus.rest-client."br.com.AntiFraudAPI.client.BankApiClient".url=${BANK_API_URL}